# Generated by Django 4.2.3 on 2023-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.BooleanField(default=False, verbose_name='My Checkbox'),
        ),
    ]
