# Generated by Django 4.2.3 on 2023-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_order_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='materials',
        ),
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.ManyToManyField(blank=True, to='schoolapp.checkbox'),
        ),
    ]
