# Generated by Django 4.2.3 on 2023-10-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_remove_order_materials_delete_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='wikipedia_url',
        ),
    ]
