# Generated by Django 4.2.3 on 2023-10-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_remove_department_wikipedia_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='username',
        ),
    ]
