# Generated by Django 4.2.3 on 2023-10-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_order_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.department'),
        ),
    ]
